services:
  - type: web
    name: tuition-platform-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-app-name.vercel.app
      - key: UPLOADS_DIR
        value: uploads
      - key: ADMIN_EMAIL
        value: admin@tuition.local
      - key: ADMIN_PASSWORD
        value: Admin123!

databases:
  - name: mongodb
    databaseName: tuitionPlatform
    user: tuition_user
